### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andre-nguyen** [hku-mars/ikd-Tree#1]
Hi,

under what license is this code distributed and can you add the license to the repository?

Thanks,

**Comment by Ecstasy-EC** [comment]
Hi, 

GNU General Public License v2.0 has been added. 

Thanks for your notice!

**Comment by Ecstasy-EC** [comment]
> Hi,
> 
> under what license is this code distributed and can you add the license to the repository?
> 
> Thanks,

Hi,

GNU General Public License v2.0 has been added.

Thanks for your notice!
