### ISSUE TITLE
max_dist in search function

### ISSUE THREAD

**Issue by traum100** [hku-mars/ikd-Tree#19]
Thanks for releasing great works.

"ikd_Tree.cpp", 886 line.
if (dist <= max_dist && (q.size() < k_nearest || dist < q.top().dist))
is it right?

or
if (dist <= max_dist*max_dist && (q.size() < k_nearest || dist < q.top().dist))

**Comment by Ecstasy-EC** [comment]
@traum100 

It should be `max_dist * max_dist` in that line. I have fixed the bugs on all the branches. 

Many thanks for your careful reading and your notice!
