### ISSUE TITLE
gpu acceleration and parallellism

### ISSUE THREAD

**Issue by Jaetriel** [hku-mars/ikd-Tree#21]
Hi, from what I can see in the code, you are using multiple threads, but all of the calculations are done by the CPU correct? Would it be possible to adjust the code to make use of the GPU using something like CUDA to be able to achieve even better performance?

**Comment by Ecstasy-EC** [comment]
@Jaetriel  
Thanks for your interest.

Applying parallelism to incremental operations is challenging, limited to the tree structure and rebalancing principles. But it could be possible to do so for the nearest search. However, we do not plan to support GPU acceleration in the recent future. 

You might do the GPU acceleration by yourself. Feel free to open issues whenever you meet problems about the data structure. I will try my best to help you.
