### ISSUE TITLE
对‘KD_TREE<POINT_TYPE>::~KD_TREE()’未定义的引用

### ISSUE THREAD

**Issue by yuchuxiang** [hku-mars/ikd-Tree#30]
我想创建一个自定义的PCL点云格式，然后使用IKD-TREE进行树的构建和搜索。
但是自定义的点云在创建树的时候代码报错：（尝试在头文件前面加上#define PCL_NO_PRECOMPILE仍然不起作用）
`CMakeFiles/mesh_mapping_test.dir/src/test.cpp.o：在函数‘std::_Sp_counted_ptr<KD_TREE<PP>*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()’中：
/usr/include/c++/11/bits/shared_ptr_base.h:348：对‘KD_TREE<PP>::~KD_TREE()’未定义的引用
CMakeFiles/mesh_mapping_test.dir/src/test.cpp.o：在函数‘main.cold’中：
/usr/include/c++/11/bits/shared_ptr_base.h:600：对‘KD_TREE<PP>::~KD_TREE()’未定义的引用`

**Comment by SharkPeppero** [comment]
请问 你后续是怎么解决自定义点云 利用ikdtree处理的呢？是对ikdtree补充了点云类型吗
