### ISSUE TITLE
can this kdtree delete points lightweight without reconstruct a new kdtree

### ISSUE THREAD

**Issue by xieqi1** [hku-mars/ikd-Tree#4]
hi 
  Thanks for sharing your work, it is a great improvement that make kdtree cost less time when add new points, however, if I want to delete some points, can this framework handle without build a new kdtree?

**Comment by XW-HKU** [comment]
yes, of course.

**Comment by Ecstasy-EC** [comment]
Yes, the ikd-Tree supports both point-wise and box-wise delete as memtioned in our preprint papaer. Please refer to our demo cpp for further information.

**Comment by xieqi1** [comment]
That's great, I will take a close look at this work.
