### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by femust** [hku-mars/ikd-Tree#5]
Hey, 

can you explain to me what's the reason  when [this](https://github.com/hku-mars/ikd-Tree/blob/78f0630c21b84b22c34f6596db8336b9eef03677/ikd_Tree.cpp#L197) triggers?

**Comment by femust** [comment]
@Ecstasy-EC @XW-HKU

**Comment by Ecstasy-EC** [comment]
@femust 
Sorry for my late reply. 
The error is resulted from the multi-thread implementation. When the second thread finishes performing all operations inside the operation logger into the newly built tree , it will move on to lock the thread and replace the original tree in the main thread. However, between the finishing time and the lock time, it is possible to have incremental operations inserted to the operation logger. Therefore there will be some incremental operations left in the logger. In the next rebuilding process in the second thread, this error msg will be triggered. 
In my test, this error only appears at the beginning of the algorithm. It seldom happens and does not harm the performance.

**Comment by femust** [comment]
@Ecstasy-EC  ok thanks for the answer
