### ISSUE TITLE
I wonder whether Nearest_Search support multi-thread operation ?

### ISSUE THREAD

**Issue by Woodpecker0** [hku-mars/ikd-Tree#6]
Thanks for your work, it's elegant and useful.

I would like to use nearest search in a openmp section, eg:

 ` 
#pragma omp parallel for num_threads(4)
for (int i = 0; i < laserCloudSurfLastDSNum; i++)
{
    PointType pointOri, pointSel, coeff;
    std::vector<int> pointSearchInd;
    std::vector<float> pointSearchSqDis;

    pointOri = laserCloudSurfLastDS->points[i];
    pointAssociateToMap(&pointOri, &pointSel); 
    kdtreeSurfFromMap->nearestKSearch(pointSel, 5, pointSearchInd, pointSearchSqDis); //replaced by ikd-tree
}
`
Is it possible to do multiple search at the same time ? It seems that  a mutex is used within the Nearest_Search(), which means that parallel operations actually save no time. Am i right ?

**Comment by Ecstasy-EC** [comment]
Sorry for my late reply.

Our ikd-Tree supports multi-thread nearest search. The mutex locks are only used to avoid memory conflicts in lazy label updates thus the multi-thread operations definitely save time. We have already tested the multi-thread nearest search in our LIO applications. So don't worry about this.
