### ISSUE TITLE
在类里面定义ikd_tree时程序崩溃

### ISSUE THREAD

**Issue by AFEICHINA** [hku-mars/ikd-Tree#8]
嗨，
    我在测试最新版本ikdtree的时候遇到一个问题，当我在类中定义ikdtree的时候，程序总是Segmentation fault (core dumped)。你能修复一下这个问题吗？
    谢谢！

**Comment by XW-HKU** [comment]
> 嗨，
> 我在测试最新版本ikdtree的时候遇到一个问题，当我在类中定义ikdtree的时候，程序总是Segmentation fault (core dumped)。你能修复一下这个问题吗？
> 谢谢！

could you append some code here to let us see what happends

**Comment by AFEICHINA** [comment]
> > 嗨，
> > 我在测试最新版本ikdtree的时候遇到一个问题，当我在类中定义ikdtree的时候，程序总是Segmentation fault (core dumped)。你能修复一下这个问题吗？
> > 谢谢！
> 
> could you append some code here to let us see what happends

Ok， I will send you an email. Thanks.

**Comment by AFEICHINA** [comment]
你好，我的测试代码如下：
`#include "ikd_Tree.h"
// KD_TREE kdtree;

class Test{
    public:
        Test(){printf("test\n");}
        KD_TREE kdtree;
};

int main(int argc, char** argv){
    printf("Testing ...\n");
    Test test;
    return 0;
}`

**Comment by AFEICHINA** [comment]
`#include "ikd_Tree.h"
// KD_TREE kdtree;

class Test{
    public:
        Test(){printf("test\n");}
        KD_TREE kdtree;
};

int main(int argc, char** argv){
    printf("Testing ...\n");
    Test test;
    return 0;
}
`
你好，这是我的测试代码，谢谢。

**Comment by Ecstasy-EC** [comment]
@AFEICHINA  Please define the ikd-Tree (and any class that includes it) as a global variable since multi-thread is required.

**Comment by AFEICHINA** [comment]
> @AFEICHINA Please define the ikd-Tree (and any class that includes it) as a global variable since multi-thread is required.

Thanks
