### ISSUE TITLE
KD_TREE::delete_tree_nodes() does not destroy push_down_mutex_lock

### ISSUE THREAD

**Issue by salovision** [hku-mars/ikd-Tree#9]
I had an issue where `KD_TREE::InitTreeNode()` didn't get valid mutex from `pthread_mutex_init()` because it ran out of handles (it returned nullptr and crashed later when accessing nullptr mutex pointer).  Then I noticed that `push_down_mutex_lock` is never destroyed when `KD_TREE_NODE` is deleted.

I added `pthread_mutex_destroy( &(*root)->push_down_mutex_lock );` to `KD_TREE::delete_tree_nodes()` and the problem went away.  So currently it leaks mutex handles which you may ran out of if you create/delete lot of nodes.

**Comment by Ecstasy-EC** [comment]
@salovision 
Thanks a lot for your issue! We did not meet this problem as we never tested that much points to delete. Will fix it soon.
